miatoll: properties: Fix duplicate prop
* Apparently it was set as true in QPR2?

error: found duplicate sysprop assignments:
ro.apex.updatable=false
ro.apex.updatable=true

Signed-off-by: clarencelol <clarencekuiek@proton.me>